### ISSUE TITLE
Is there any plan to add .Net standard 2.0 as a target platform?

### ISSUE THREAD

**Issue by dariogriffo** [rebus-org/Rebus.Msmq#2]
I'm starting a new project to run on .NET core and want to know the support of MSMQ with .NET standard, since I see Rebus, and Rebus.AzureServiceBus already have it

**Comment by dariogriffo** [comment]
I think [this](https://github.com/dotnet/corefx/issues/6204) replies to my question.

**Comment by mookid8000** [comment]
> Is there any plan to add .Net standard 2.0 as a target platform

Yes, definitely! As soon as it makes sense to do so!

If .NET Core 3 brings System.Messaging with it, it will be pretty easy to target a suitable .NET Standard interface.

Thanks for bringing my attention to the fact the people are actually requesting that MSMQ be included in the .NET Core family! 👍

**Comment by dariogriffo** [comment]
Yes I have also liked and left a comment on the issue.
I will need to solve my problems with .net fwk

**Comment by alkampfergit** [comment]
+1 It would be nice to be useful to target .NET standard 2.2.

**Comment by mookid8000** [comment]
I am closing this issue, because there doesn't appear to be any plans from Microsoft to release support for MSMQ in .NET Standard/.NET Core.

Some people have suggested that Microsoft release the code for the MSMQ driver (i.e. the System.Messaging assembly from .NET fx), which would be pretty awesome. I am crossing my fingers that someone within Microsoft will find the time to do that.

**Comment by dev-in-disguise** [comment]
I would love to have a netstandard version of this package too. Because otherwise in my company we'd have to either switch our way of communication or stay on framework forever. None of those options sound very compelling to me.

Therefore I searched around a bit and found [this issue](https://github.com/microsoft/referencesource/pull/141). This basically means there is already a .net standard version of `System.Messaging` since July 2020 in [this nuget package](https://www.nuget.org/packages/MSMQ.Messaging/). Though according to the comments not every MSMQ functionality seems to be supported. 

So based on this new information do you plan to integrate this? Or in case of time issues is there any way I could support you here?

**Comment by mookid8000** [comment]
I didn't know the  MSMQ.Messaging package existed!

Rebus has had https://www.nuget.org/packages/Rebus.Msmq.Experimental for a while now, but it would definitely be interested to see if MSMQ.Messaging would be a better bet.

**Comment by dev-in-disguise** [comment]
If you want to I can test the migration with this other package and open up the PR when I'm done. Would this be alright for you? 

And thanks for the hint on the experimental package! In the meantime I'm working just on a prototype for our migration to .net 6 so this is a perfect fit for now

**Comment by mookid8000** [comment]
Well, I don't have any strong opinion on whether to use [experimental.system.messaging](https://www.nuget.org/packages/experimental.system.messaging/) or [MSMQ.Messaging](https://www.nuget.org/packages/MSMQ.Messaging/), but if you can find a good reason to pick one of them over the other, then it would be awesome to integrate it.
